apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcar-services
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: main-service
          image: europe-west1-docker.pkg.dev/qcar-backend/qcar-backend-repo/main_service:0.0.8
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: main-service
spec:
  selector:
    app: webserver
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  type: LoadBalancer