kind: Deployment
apiVersion: apps/v1
metadata:
  name: qcar-deployment
  labels:
    app: qcar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qcar
  template:
    metadata:
      labels:
        app: qcar
    spec:
      containers:
      - name: main-service
        image: dylar/qcar-backend:0.0.12 #europe-west1-docker.pkg.dev/qcar-backend/qcar-backend-repo/main_service:0.0.12
        ports:
        - containerPort: 2203
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/opt/firebase/qcar-firebase-adminsdk.json"
        volumeMounts:
          - name: secret-volume
            mountPath: "/opt/firebase"
            readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: firestore-secret
---
kind: Service
apiVersion: v1
metadata:
  name: qcar-service
spec:
  type: LoadBalancer
  selector:
    app: qcar
  ports:
  - name: backend
    port: 1110
    targetPort: 2203
    protocol: TCP
