kind: Deployment
apiVersion: apps/v1
metadata:
  name: qcar-deployment
  labels:
    app: qcar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qcar
  template:
    metadata:
      labels:
      app: qcar
    spec:
      containers:
        name: main-service
        image: europe-west1-docker.pkg.dev/qcar-backend/qcar-backend-repo/main_service:0.0.9
        ports:
          containerPort: 2203
        env:
          name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretRef:
              name: firestore-secret
              key: FIRESTORE_CREDENTIALS
---
kind: Service
apiVersion: v1
metadata:
  name: qcar-service
spec:
  selector:
    app: qcar
  ports:
    port: 1110
    targetPort: 2203
    protocol: TCP
    name: http
  type: LoadBalancer