kind: Deployment
apiVersion: apps/v1
metadata:
  name: qcar-deployment
  labels:
    app: qcar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qcar
  template:
    metadata:
      labels:
        app: qcar
    spec:
      containers:
        - name: main-service
          image: europe-west1-docker.pkg.dev/qcar-backend/qcar-backend-repo/main_service:0.0.8
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: qcar-service
spec:
  selector:
    app: qcar
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: LoadBalancer